export const BASE_URL = import.meta.env.VITE_BACKEND_URL;

export const companies = [
  { id: 1, value: "abb", label: "ABB" },
  { id: 2, value: "abbyy", label: "ABBYY" },
  { id: 3, value: "accenture", label: "Accenture" },
  { id: 4, value: "acer", label: "Acer" },
  { id: 5, value: "actifio", label: "Actifio" },
  { id: 6, value: "adobe", label: "Adobe" },
  { id: 7, value: "adobeanalytics", label: "Adobe Analytics" },
  { id: 8, value: "advanced", label: "Advanced" },
  { id: 9, value: "agilent", label: "Agilent Technologies" },
  { id: 10, value: "airbus", label: "Airbus" },
  { id: 11, value: "airtel", label: "Bharti Airtel" },
  { id: 12, value: "akamai", label: "Akamai Technologies" },
  { id: 13, value: "alcatel", label: "Alcatel-Lucent" },
  { id: 14, value: "algolia", label: "Algolia" },
  { id: 15, value: "alibaba", label: "Alibaba Group" },
  { id: 16, value: "allscripts", label: "Allscripts" },
  { id: 17, value: "alphabet", label: "Alphabet Inc." },
  { id: 18, value: "altassian", label: "Atlassian" },
  { id: 19, value: "alteryx", label: "Alteryx" },
  { id: 20, value: "amazon", label: "Amazon" },
  { id: 21, value: "amazonwebservices", label: "Amazon Web Services" },
  { id: 22, value: "amd", label: "AMD" },
  { id: 23, value: "americanexpress", label: "American Express" },
  { id: 24, value: "amdocs", label: "Amdocs" },
  { id: 25, value: "amphenol", label: "Amphenol" },
  { id: 26, value: "anaplan", label: "Anaplan" },
  { id: 27, value: "ansible", label: "Ansible" },
  { id: 28, value: "anthology", label: "Anthology" },
  { id: 29, value: "apache", label: "Apache Software Foundation" },
  { id: 30, value: "api", label: "API" },
  { id: 31, value: "apigee", label: "Apigee" },
  { id: 32, value: "apple", label: "Apple" },
  { id: 33, value: "applitools", label: "Applitools" },
  { id: 34, value: "apptio", label: "Apptio" },
  { id: 35, value: "aptean", label: "Aptean" },
  { id: 36, value: "arcserve", label: "Arcserve" },
  { id: 37, value: "arm", label: "ARM Holdings" },
  { id: 38, value: "aruba", label: "Aruba Networks" },
  { id: 39, value: "asana", label: "Asana" },
  { id: 40, value: "asus", label: "ASUS" },
  { id: 41, value: "atos", label: "Atos" },
  { id: 42, value: "attunity", label: "Attunity" },
  { id: 43, value: "autodesk", label: "Autodesk" },
  { id: 44, value: "automatic", label: "Automattic" },
  { id: 45, value: "avaya", label: "Avaya" },
  { id: 46, value: "avnet", label: "Avnet" },
  { id: 47, value: "axisbank", label: "Axis Bank" },
  { id: 48, value: "bajajfinserv", label: "Bajaj Finserv" },
  { id: 49, value: "bandhanbank", label: "Bandhan Bank" },
  { id: 50, value: "barclays", label: "Barclays" },
  { id: 51, value: "basware", label: "Basware" },
  { id: 52, value: "bentley", label: "Bentley Systems" },
  { id: 53, value: "bigbasket", label: "BigBasket" },
  { id: 54, value: "bigcommerce", label: "BigCommerce" },
  { id: 55, value: "blackberry", label: "BlackBerry" },
  { id: 56, value: "blackrock", label: "BlackRock" },
  { id: 57, value: "bluecoat", label: "Blue Coat Systems" },
  { id: 58, value: "bluejeans", label: "BlueJeans" },
  { id: 59, value: "blueshift", label: "Blueshift" },
  { id: 60, value: "boeing", label: "Boeing" },
  { id: 61, value: "bookmyshow", label: "BookMyShow" },
  { id: 62, value: "bosch", label: "Bosch" },
  { id: 63, value: "box", label: "Box" },
  { id: 64, value: "broadcom", label: "Broadcom" },
  { id: 65, value: "brocade", label: "Brocade" },
  { id: 66, value: "byju", label: "BYJU'S" },
  { id: 67, value: "cadence", label: "Cadence Design Systems" },
  { id: 68, value: "calpine", label: "Calpine Corporation" },
  { id: 69, value: "canonical", label: "Canonical" },
  { id: 70, value: "capgemini", label: "Capgemini" },
  { id: 71, value: "carbonite", label: "Carbonite" },
  { id: 72, value: "careem", label: "Careem" },
  { id: 73, value: "cassandra", label: "Cassandra" },
  { id: 74, value: "catalytic", label: "Catalytic" },
  { id: 75, value: "cbre", label: "CBRE Group" },
  { id: 76, value: "cdw", label: "CDW Corporation" },
  { id: 77, value: "celonis", label: "Celonis" },
  { id: 78, value: "cerner", label: "Cerner Corporation" },
  { id: 79, value: "cgi", label: "CGI" },
  { id: 80, value: "chargebee", label: "Chargebee" },
  { id: 81, value: "checkpoint", label: "Check Point Software" },
  { id: 82, value: "chef", label: "Chef Software" },
  { id: 83, value: "circleci", label: "CircleCI" },
  { id: 84, value: "cisco", label: "Cisco Systems" },
  { id: 85, value: "citi", label: "Citigroup" },
  { id: 86, value: "citrix", label: "Citrix Systems" },
  { id: 87, value: "cleartrip", label: "Cleartrip" },
  { id: 88, value: "cloudera", label: "Cloudera" },
  { id: 89, value: "cloudflare", label: "Cloudflare" },
  { id: 90, value: "cloudinary", label: "Cloudinary" },
  { id: 91, value: "cloudstrike", label: "CrowdStrike" },
  { id: 92, value: "coforge", label: "Coforge" },
  { id: 93, value: "cognizant", label: "Cognizant" },
  { id: 94, value: "commvault", label: "Commvault" },
  { id: 95, value: "compuware", label: "Compuware" },
  { id: 96, value: "confluent", label: "Confluent" },
  { id: 97, value: "container", label: "Container Solutions" },
  { id: 98, value: "contentful", label: "Contentful" },
  { id: 99, value: "couchbase", label: "Couchbase" },
  { id: 100, value: "coursera", label: "Coursera" },
  { id: 101, value: "curefit", label: "Cure.fit" },
  { id: 102, value: "cyberark", label: "CyberArk" },
  { id: 103, value: "cyient", label: "Cyient" },
  { id: 104, value: "dailyhunt", label: "DailyHunt" },
  { id: 105, value: "databricks", label: "Databricks" },
  { id: 106, value: "datadog", label: "Datadog" },
  { id: 107, value: "dataminr", label: "Dataminr" },
  { id: 108, value: "datastax", label: "DataStax" },
  { id: 109, value: "dell", label: "Dell Technologies" },
  { id: 110, value: "deloitte", label: "Deloitte" },
  { id: 111, value: "deutsche", label: "Deutsche Bank" },
  { id: 112, value: "digitalocean", label: "DigitalOcean" },
  { id: 113, value: "directi", label: "Directi" },
  { id: 114, value: "disney", label: "Disney" },
  { id: 115, value: "docker", label: "Docker" },
  { id: 116, value: "dolby", label: "Dolby Laboratories" },
  { id: 117, value: "dream11", label: "Dream11" },
  { id: 118, value: "dropbox", label: "Dropbox" },
  { id: 119, value: "druva", label: "Druva" },
  { id: 120, value: "dxc", label: "DXC Technology" },
  { id: 121, value: "dynatrace", label: "Dynatrace" },
  { id: 122, value: "ea", label: "Electronic Arts" },
  { id: 123, value: "ebay", label: "eBay" },
  { id: 124, value: "elastic", label: "Elastic" },
  { id: 125, value: "emc", label: "EMC Corporation" },
  { id: 126, value: "emerson", label: "Emerson" },
  { id: 127, value: "epicor", label: "Epicor Software" },
  { id: 128, value: "ericsson", label: "Ericsson" },
  { id: 129, value: "ey", label: "Ernst & Young" },
  { id: 130, value: "expedia", label: "Expedia Group" },
  { id: 131, value: "facebook", label: "Meta (Facebook)" },
  { id: 132, value: "factset", label: "FactSet" },
  { id: 133, value: "fastly", label: "Fastly" },
  { id: 134, value: "federalbank", label: "Federal Bank" },
  { id: 135, value: "fidelity", label: "Fidelity Investments" },
  { id: 136, value: "fireeye", label: "FireEye" },
  { id: 137, value: "fitbit", label: "Fitbit" },
  { id: 138, value: "flipkart", label: "Flipkart" },
  { id: 139, value: "flock", label: "Flock" },
  { id: 140, value: "fortinet", label: "Fortinet" },
  { id: 141, value: "fractal", label: "Fractal Analytics" },
  { id: 142, value: "freshworks", label: "Freshworks" },
  { id: 143, value: "fujitsu", label: "Fujitsu" },
  { id: 144, value: "gartner", label: "Gartner" },
  { id: 145, value: "ge", label: "General Electric" },
  { id: 146, value: "genesys", label: "Genesys" },
  { id: 147, value: "github", label: "GitHub" },
  { id: 148, value: "gitlab", label: "GitLab" },
  { id: 149, value: "globallogic", label: "GlobalLogic" },
  { id: 150, value: "gojek", label: "Gojek" },
  { id: 151, value: "goldmansachs", label: "Goldman Sachs" },
  { id: 152, value: "google", label: "Google" },
  { id: 153, value: "grab", label: "Grab" },
  { id: 154, value: "grafana", label: "Grafana Labs" },
  { id: 155, value: "grofers", label: "Blinkit (Grofers)" },
  { id: 156, value: "guidewire", label: "Guidewire Software" },
  { id: 157, value: "hadoop", label: "Apache Hadoop" },
  { id: 158, value: "hashicorp", label: "HashiCorp" },
  { id: 159, value: "hcl", label: "HCL Technologies" },
  { id: 160, value: "hdfcbank", label: "HDFC Bank" },
  { id: 161, value: "hexaware", label: "Hexaware Technologies" },
  { id: 162, value: "hike", label: "Hike Messenger" },
  { id: 163, value: "hitachi", label: "Hitachi Vantara" },
  { id: 164, value: "honeywell", label: "Honeywell" },
  { id: 165, value: "hotstar", label: "Disney+ Hotstar" },
  { id: 166, value: "hp", label: "HP Inc." },
  { id: 167, value: "hpe", label: "Hewlett Packard Enterprise" },
  { id: 168, value: "hubspot", label: "HubSpot" },
  { id: 169, value: "huawei", label: "Huawei Technologies" },
  { id: 170, value: "ibm", label: "IBM" },
  { id: 171, value: "icicbank", label: "ICICI Bank" },
  { id: 172, value: "idfcfirst", label: "IDFC First Bank" },
  { id: 173, value: "ifs", label: "IFS" },
  { id: 174, value: "igt", label: "IGT" },
  { id: 175, value: "impetus", label: "Impetus Technologies" },
  { id: 176, value: "indusind", label: "IndusInd Bank" },
  { id: 177, value: "informatica", label: "Informatica" },
  { id: 178, value: "infosys", label: "Infosys" },
  { id: 179, value: "inmobi", label: "InMobi" },
  { id: 180, value: "innovaccer", label: "Innovaccer" },
  { id: 181, value: "instacart", label: "Instacart" },
  { id: 182, value: "instagram", label: "Instagram" },
  { id: 183, value: "intel", label: "Intel Corporation" },
  { id: 184, value: "intuit", label: "Intuit" },
  { id: 185, value: "iqvia", label: "IQVIA" },
  { id: 186, value: "jenkins", label: "Jenkins" },
  { id: 187, value: "jio", label: "Reliance Jio" },
  { id: 188, value: "jira", label: "Atlassian Jira" },
  { id: 189, value: "jpmorgan", label: "JPMorgan Chase" },
  { id: 190, value: "juniper", label: "Juniper Networks" },
  { id: 191, value: "just", label: "Just Dial" },
  { id: 192, value: "kafka", label: "Apache Kafka" },
  { id: 193, value: "kellton", label: "Kellton Tech" },
  { id: 194, value: "kpmg", label: "KPMG" },
  { id: 195, value: "kubernetes", label: "Kubernetes" },
  { id: 196, value: "larsen", label: "L&T Technology Services" },
  { id: 197, value: "lenskart", label: "Lenskart" },
  { id: 198, value: "lenovo", label: "Lenovo" },
  { id: 199, value: "lexisnexis", label: "LexisNexis" },
  { id: 200, value: "lg", label: "LG Electronics" },
  { id: 201, value: "linkedin", label: "LinkedIn" },
  { id: 202, value: "lti", label: "L&T Infotech" },
  { id: 203, value: "ltimindtree", label: "LTIMindtree" },
  { id: 204, value: "lyft", label: "Lyft" },
  { id: 205, value: "mahindra", label: "Tech Mahindra" },
  { id: 206, value: "makemytrip", label: "MakeMyTrip" },
  { id: 207, value: "mapbox", label: "Mapbox" },
  { id: 208, value: "mariadb", label: "MariaDB" },
  { id: 209, value: "marketo", label: "Marketo" },
  { id: 210, value: "mastercard", label: "Mastercard" },
  { id: 211, value: "mcafee", label: "McAfee" },
  { id: 212, value: "mckinsey", label: "McKinsey & Company" },
  { id: 213, value: "mediatek", label: "MediaTek" },
  { id: 214, value: "meesho", label: "Meesho" },
  { id: 215, value: "mendix", label: "Mendix" },
  { id: 216, value: "mercari", label: "Mercari" },
  { id: 217, value: "meta", label: "Meta" },
  { id: 218, value: "microfocus", label: "Micro Focus" },
  { id: 219, value: "microsoft", label: "Microsoft" },
  { id: 220, value: "mindtree", label: "Mindtree" },
  { id: 221, value: "mongodb", label: "MongoDB" },
  { id: 222, value: "morganstanley", label: "Morgan Stanley" },
  { id: 223, value: "motorola", label: "Motorola Solutions" },
  { id: 224, value: "mphasis", label: "Mphasis" },
  { id: 225, value: "mpl", label: "Mobile Premier League" },
  { id: 226, value: "mu", label: "Mu Sigma" },
  { id: 227, value: "myntra", label: "Myntra" },
  { id: 228, value: "mysql", label: "MySQL" },
  { id: 229, value: "nagarro", label: "Nagarro" },
  { id: 230, value: "nasdaq", label: "NASDAQ" },
  { id: 231, value: "netapp", label: "NetApp" },
  { id: 232, value: "netflix", label: "Netflix" },
  { id: 233, value: "newrelic", label: "New Relic" },
  { id: 234, value: "nextiva", label: "Nextiva" },
  { id: 235, value: "nice", label: "NICE" },
  { id: 236, value: "nike", label: "Nike" },
  { id: 237, value: "nineleaps", label: "NineLeaps" },
  { id: 238, value: "nokia", label: "Nokia" },
  { id: 239, value: "notion", label: "Notion" },
  { id: 240, value: "nttdata", label: "NTT DATA" },
  { id: 241, value: "nutanix", label: "Nutanix" },
  { id: 242, value: "nvidia", label: "NVIDIA" },
  { id: 243, value: "nykaa", label: "Nykaa" },
  { id: 244, value: "ola", label: "Ola" },
  { id: 245, value: "oneplus", label: "OnePlus" },
  { id: 246, value: "onetrust", label: "OneTrust" },
  { id: 247, value: "oppo", label: "OPPO" },
  { id: 248, value: "oracle", label: "Oracle" },
  { id: 249, value: "outbrain", label: "Outbrain" },
  { id: 250, value: "palantir", label: "Palantir Technologies" },
  { id: 251, value: "palo", label: "Palo Alto Networks" },
  { id: 252, value: "panasonic", label: "Panasonic" },
  { id: 253, value: "paypal", label: "PayPal" },
  { id: 254, value: "paytm", label: "Paytm" },
  { id: 255, value: "pegasystems", label: "Pegasystems" },
  { id: 256, value: "persistent", label: "Persistent Systems" },
  { id: 257, value: "phonepe", label: "PhonePe" },
  { id: 258, value: "ping", label: "Ping Identity" },
  { id: 259, value: "pinterest", label: "Pinterest" },
  { id: 260, value: "pivotal", label: "Pivotal Software" },
  { id: 261, value: "policybazaar", label: "PolicyBazaar" },
  { id: 262, value: "postman", label: "Postman" },
  { id: 263, value: "publicis", label: "Publicis Sapient" },
  { id: 264, value: "puppet", label: "Puppet" },
  { id: 265, value: "pwc", label: "PwC" },
  { id: 266, value: "qlik", label: "Qlik" },
  { id: 267, value: "qualcomm", label: "Qualcomm" },
  { id: 268, value: "quantiphi", label: "Quantiphi" },
  { id: 269, value: "quora", label: "Quora" },
  { id: 270, value: "razorpay", label: "Razorpay" },
  { id: 271, value: "rbl", label: "RBL Bank" },
  { id: 272, value: "realme", label: "Realme" },
  { id: 273, value: "rcom", label: "Reliance Communications" },
  { id: 274, value: "redis", label: "Redis" },
  { id: 275, value: "redhat", label: "Red Hat" },
  { id: 276, value: "reliance", label: "Reliance Industries" },
  { id: 277, value: "riverbed", label: "Riverbed Technology" },
  { id: 278, value: "rockwell", label: "Rockwell Automation" },
  { id: 279, value: "roku", label: "Roku" },
  { id: 280, value: "rubrik", label: "Rubrik" },
  { id: 281, value: "sage", label: "Sage" },
  { id: 282, value: "salesforce", label: "Salesforce" },
  { id: 283, value: "samsung", label: "Samsung" },
  { id: 284, value: "sap", label: "SAP" },
  { id: 285, value: "sbi", label: "State Bank of India" },
  { id: 286, value: "schneider", label: "Schneider Electric" },
  { id: 287, value: "seagate", label: "Seagate Technology" },
  { id: 288, value: "sendgrid", label: "SendGrid" },
  { id: 289, value: "servicenow", label: "ServiceNow" },
  { id: 290, value: "sharechat", label: "ShareChat" },
  { id: 291, value: "shopify", label: "Shopify" },
  { id: 292, value: "siemens", label: "Siemens" },
  { id: 293, value: "slack", label: "Slack Technologies" },
  { id: 294, value: "snapchat", label: "Snap Inc." },
  { id: 295, value: "snapdeal", label: "Snapdeal" },
  { id: 296, value: "snowflake", label: "Snowflake" },
  { id: 297, value: "softbank", label: "SoftBank" },
  { id: 298, value: "sonicwall", label: "SonicWall" },
  { id: 299, value: "sony", label: "Sony" },
  { id: 300, value: "spacex", label: "SpaceX" },
  { id: 301, value: "splunk", label: "Splunk" },
  { id: 302, value: "spotify", label: "Spotify" },
  { id: 303, value: "square", label: "Square" },
  { id: 304, value: "standardchartered", label: "Standard Chartered" },
  { id: 305, value: "starbucks", label: "Starbucks Technology" },
  { id: 306, value: "sterlite", label: "Sterlite Technologies" },
  { id: 307, value: "stripe", label: "Stripe" },
  { id: 308, value: "sumo", label: "Sumo Logic" },
  { id: 309, value: "swiggy", label: "Swiggy" },
  { id: 310, value: "synopsys", label: "Synopsys" },
  { id: 311, value: "tableau", label: "Tableau" },
  { id: 312, value: "takeaway", label: "Just Eat Takeaway" },
  { id: 313, value: "talend", label: "Talend" },
  { id: 314, value: "tata", label: "Tata Consultancy Services" },
  { id: 315, value: "tatacomm", label: "Tata Communications" },
  { id: 316, value: "tatasteel", label: "Tata Steel" },
  { id: 317, value: "tcs", label: "TCS" },
  { id: 318, value: "teamviewer", label: "TeamViewer" },
  { id: 319, value: "techmahindra", label: "Tech Mahindra" },
  { id: 320, value: "teradata", label: "Teradata" },
  { id: 321, value: "tesla", label: "Tesla" },
  { id: 322, value: "thoughtworks", label: "Thoughtworks" },
  { id: 323, value: "tibco", label: "TIBCO Software" },
  { id: 324, value: "tiger", label: "Tiger Analytics" },
  { id: 325, value: "tiktok", label: "TikTok" },
  { id: 326, value: "tinder", label: "Tinder" },
  { id: 327, value: "toshiba", label: "Toshiba" },
  { id: 328, value: "trello", label: "Trello" },
  { id: 329, value: "twilio", label: "Twilio" },
  { id: 330, value: "twitter", label: "Twitter" },
  { id: 331, value: "tvsmotor", label: "TVS Motor" },
  { id: 332, value: "uber", label: "Uber" },
  { id: 333, value: "uipath", label: "UiPath" },
  { id: 334, value: "unacademy", label: "Unacademy" },
  { id: 335, value: "unity", label: "Unity Technologies" },
  { id: 336, value: "urbancompany", label: "Urban Company" },
  { id: 337, value: "varian", label: "Varian Medical Systems" },
  { id: 338, value: "vedantu", label: "Vedantu" },
  { id: 339, value: "veeva", label: "Veeva Systems" },
  { id: 340, value: "veeam", label: "Veeam Software" },
  { id: 341, value: "veritas", label: "Veritas Technologies" },
  { id: 342, value: "verizon", label: "Verizon" },
  { id: 343, value: "vmware", label: "VMware" },
  { id: 344, value: "visa", label: "Visa" },
  { id: 345, value: "vivo", label: "Vivo" },
  { id: 346, value: "vodafone", label: "Vodafone Idea" },
  { id: 347, value: "walmart", label: "Walmart Global Tech" },
  { id: 348, value: "wavemaker", label: "WaveMaker" },
  { id: 349, value: "webex", label: "Webex" },
  { id: 350, value: "wells", label: "Wells Fargo" },
  { id: 351, value: "westerndigital", label: "Western Digital" },
  { id: 352, value: "whatsapp", label: "WhatsApp" },
  { id: 353, value: "wipro", label: "Wipro" },
  { id: 354, value: "workday", label: "Workday" },
  { id: 355, value: "xiaomi", label: "Xiaomi" },
  { id: 356, value: "xerox", label: "Xerox" },
  { id: 357, value: "xero", label: "Xero" },
  { id: 358, value: "yahoo", label: "Yahoo" },
];

export const programmingLanguages = [
  { id: 1, label: "JavaScript", value: "javascript" },
  { id: 2, label: "Python", value: "python" },
  { id: 3, label: "Java", value: "java" },
  { id: 4, label: "C++", value: "cpp" },
  { id: 5, label: "C#", value: "csharp" },
  { id: 6, label: "TypeScript", value: "typescript" },
  { id: 7, label: "Go", value: "go" },
  { id: 8, label: "Ruby", value: "ruby" },
  { id: 9, label: "PHP", value: "php" },
  { id: 10, label: "Swift", value: "swift" },
  { id: 11, label: "Kotlin", value: "kotlin" },
  { id: 12, label: "Rust", value: "rust" },
  { id: 18, label: "C", value: "c" },
  { id: 20, label: "R", value: "r" },
];

export const historyOptions = [
  { id: 1, label: "All", value: "all_sessions" },
  { id: 2, label: "Interview", value: "interview_sessions" },
  { id: 3, label: "OATest", value: "oatest_sessions" },
  { id: 4, label: "Pending", value: "pending_sessions" },
];

export const roles = [
  { id: 1, label: "Software Developer", value: "software_developer" },
  { id: 2, label: "Backend Developer", value: "backend_developer" },
  { id: 3, label: "Frontend Developer", value: "frontend_developer" },
  { id: 4, label: "Full Stack Developer", value: "full_stack_developer" },
  { id: 5, label: "Mobile App Developer", value: "mobile_app_developer" },
  { id: 6, label: "DevOps Engineer", value: "devops_engineer" },
  { id: 7, label: "Cloud Engineer", value: "cloud_engineer" },
  { id: 8, label: "Data Scientist", value: "data_scientist" },
  { id: 9, label: "Machine Learning Engineer", value: "ml_engineer" },
  { id: 10, label: "AI Engineer", value: "ai_engineer" },
  { id: 11, label: "QA Engineer / Tester", value: "qa_engineer" },
  { id: 12, label: "UI/UX Designer", value: "ui_ux_designer" },
  { id: 13, label: "Database Administrator", value: "database_administrator" },
  { id: 14, label: "Cybersecurity Analyst", value: "cybersecurity_analyst" },
  { id: 15, label: "System Administrator", value: "system_administrator" },
  { id: 16, label: "Network Engineer", value: "network_engineer" },
  {
    id: 17,
    label: "Site Reliability Engineer (SRE)",
    value: "site_reliability_engineer",
  },
  { id: 18, label: "Game Developer", value: "game_developer" },
  { id: 19, label: "Blockchain Developer", value: "blockchain_developer" },
  { id: 20, label: "Product Manager", value: "product_manager" },
];

export const experienceLevels = [
  { id: 1, label: "Internship", value: "Internship" },
  { id: 2, label: "Entry Level (0-1 years)", value: "Entry Level" },
  { id: 3, label: "Junior (1-3 years)", value: "Junior" },
  { id: 4, label: "Mid-Level (3-5 years)", value: "Mid Level" },
  { id: 5, label: "Senior (5-8 years)", value: "Senior" },
  { id: 6, label: "Lead (8-12 years)", value: "Lead" },
  { id: 7, label: "Principal (12+ years)", value: "Principal" },
];

export const focusAreas = [
  { id: 1, label: "Coding", value: "coding" },
  { id: 2, label: "Behavioral", value: "behavioral" },
  { id: 3, label: "System Design", value: "system_design" },
  { id: 4, label: "Data Structures & Algorithms", value: "dsa" },
  { id: 5, label: "Problem Solving", value: "problem_solving" },
  { id: 6, label: "Aptitude", value: "aptitude" },
  { id: 7, label: "Communication Skills", value: "Communication Skills" },
  { id: 8, label: "Leadership & Teamwork", value: "Leadership & Teamwork" },
];

export const difficultyLevels = ["Easy", "Medium", "Hard", "Expert"];

export const durationOptions = ["Short", "Medium", "Long"];

export const skills = [
  { id: 39, value: "dotnetcore", label: ".NET Core" },
  { id: 124, value: "androidstudio", label: "Android Studio" },
  { id: 22, value: "angular", label: "Angular" },
  { id: 60, value: "ansible", label: "Ansible" },
  { id: 88, value: "antdesign", label: "Ant Design" },
  { id: 142, value: "apache", label: "Apache" },
  { id: 107, value: "airflow", label: "Apache Airflow" },
  { id: 106, value: "kafka", label: "Apache Kafka" },
  { id: 105, value: "spark", label: "Apache Spark" },
  { id: 40, value: "aspnet", label: "ASP.NET" },
  { id: 51, value: "aws", label: "AWS" },
  { id: 133, value: "lambda", label: "AWS Lambda" },
  { id: 52, value: "azure", label: "Azure" },
  { id: 134, value: "azurefunctions", label: "Azure Functions" },
  { id: 69, value: "babel", label: "Babel" },
  { id: 117, value: "bash", label: "Bash" },
  { id: 103, value: "bigdata", label: "Big Data" },
  { id: 63, value: "bitbucket", label: "Bitbucket" },
  { id: 85, value: "bootstrap", label: "Bootstrap" },
  { id: 90, value: "bulma", label: "Bulma" },
  { id: 4, value: "csharp", label: "C#" },
  { id: 5, value: "cplusplus", label: "C++" },
  { id: 49, value: "cassandra", label: "Cassandra" },
  { id: 146, value: "cdn", label: "CDN" },
  { id: 113, value: "centos", label: "CentOS" },
  { id: 78, value: "chai", label: "Chai" },
  { id: 89, value: "chakraui", label: "Chakra UI" },
  { id: 145, value: "cloudflare", label: "Cloudflare" },
  { id: 65, value: "confluence", label: "Confluence" },
  { id: 83, value: "cordova", label: "Cordova" },
  { id: 18, value: "css", label: "CSS" },
  { id: 73, value: "cypress", label: "Cypress" },
  { id: 151, value: "data_structures_and_algorithm", label: "DSA" },
  { id: 101, value: "dataanalysis", label: "Data Analysis" },
  { id: 102, value: "datavisualization", label: "Data Visualization" },
  { id: 92, value: "deeplearning", label: "Deep Learning" },
  { id: 140, value: "digitalocean", label: "DigitalOcean" },
  { id: 147, value: "dns", label: "DNS" },
  { id: 54, value: "docker", label: "Docker" },
  { id: 31, value: "django", label: "Django" },
  { id: 50, value: "dynamodb", label: "DynamoDB" },
  { id: 122, value: "eclipse", label: "Eclipse" },
  { id: 84, value: "electronjs", label: "Electron.js" },
  { id: 45, value: "elasticsearch", label: "Elasticsearch" },
  { id: 70, value: "eslint", label: "ESLint" },
  { id: 28, value: "express", label: "Express.js" },
  { id: 30, value: "fastify", label: "Fastify" },
  { id: 33, value: "fastapi", label: "FastAPI" },
  { id: 135, value: "firebase", label: "Firebase" },
  { id: 32, value: "flask", label: "Flask" },
  { id: 80, value: "flutter", label: "Flutter" },
  { id: 61, value: "git", label: "Git" },
  { id: 62, value: "github", label: "GitHub" },
  { id: 57, value: "githubactions", label: "GitHub Actions" },
  { id: 58, value: "gitlab", label: "GitLab CI/CD" },
  { id: 9, value: "go", label: "Go" },
  { id: 53, value: "gcp", label: "Google Cloud Platform" },
  { id: 128, value: "graphql", label: "GraphQL" },
  { id: 104, value: "hadoop", label: "Hadoop" },
  { id: 139, value: "heroku", label: "Heroku" },
  { id: 17, value: "html", label: "HTML" },
  { id: 144, value: "iis", label: "IIS" },
  { id: 126, value: "insomnia", label: "Insomnia" },
  { id: 121, value: "intellij", label: "IntelliJ IDEA" },
  { id: 82, value: "ionic", label: "Ionic" },
  { id: 3, value: "java", label: "Java" },
  { id: 1, value: "javascript", label: "JavaScript" },
  { id: 56, value: "jenkins", label: "Jenkins" },
  { id: 72, value: "jest", label: "Jest" },
  { id: 64, value: "jira", label: "Jira" },
  { id: 75, value: "junit", label: "JUnit" },
  { id: 100, value: "jupyter", label: "Jupyter" },
  { id: 150, value: "jwt", label: "JWT" },
  { id: 12, value: "kotlin", label: "Kotlin" },
  { id: 55, value: "kubernetes", label: "Kubernetes" },
  { id: 36, value: "laravel", label: "Laravel" },
  { id: 20, value: "less", label: "Less" },
  { id: 111, value: "linux", label: "Linux" },
  { id: 91, value: "machinelearning", label: "Machine Learning" },
  { id: 116, value: "macos", label: "macOS" },
  { id: 87, value: "materialui", label: "Material-UI" },
  { id: 15, value: "matlab", label: "MATLAB" },
  { id: 98, value: "matplotlib", label: "Matplotlib" },
  { id: 131, value: "microservices", label: "Microservices" },
  { id: 77, value: "mocha", label: "Mocha" },
  { id: 43, value: "mongodb", label: "MongoDB" },
  { id: 41, value: "mysql", label: "MySQL" },
  { id: 29, value: "nestjs", label: "NestJS" },
  { id: 137, value: "netlify", label: "Netlify" },
  { id: 25, value: "nextjs", label: "Next.js" },
  { id: 141, value: "nginx", label: "Nginx" },
  { id: 27, value: "nodejs", label: "Node.js" },
  { id: 97, value: "numpy", label: "NumPy" },
  { id: 26, value: "nuxtjs", label: "Nuxt.js" },
  { id: 149, value: "oauth", label: "OAuth" },
  { id: 47, value: "oracle", label: "Oracle" },
  { id: 96, value: "pandas", label: "Pandas" },
  { id: 7, value: "php", label: "PHP" },
  { id: 125, value: "postman", label: "Postman" },
  { id: 42, value: "postgresql", label: "PostgreSQL" },
  { id: 108, value: "powerbi", label: "Power BI" },
  { id: 118, value: "powershell", label: "PowerShell" },
  { id: 71, value: "prettier", label: "Prettier" },
  { id: 76, value: "pytest", label: "PyTest" },
  { id: 2, value: "python", label: "Python" },
  { id: 94, value: "pytorch", label: "PyTorch" },
  { id: 110, value: "qlik", label: "Qlik" },
  { id: 14, value: "r", label: "R" },
  { id: 21, value: "react", label: "React" },
  { id: 79, value: "reactnative", label: "React Native" },
  { id: 44, value: "redis", label: "Redis" },
  { id: 114, value: "redhat", label: "Red Hat" },
  { id: 129, value: "restapi", label: "REST API" },
  { id: 8, value: "ruby", label: "Ruby" },
  { id: 38, value: "rubyonrails", label: "Ruby on Rails" },
  { id: 10, value: "rust", label: "Rust" },
  { id: 19, value: "sass", label: "Sass" },
  { id: 13, value: "scala", label: "Scala" },
  { id: 95, value: "scikitlearn", label: "Scikit-learn" },
  { id: 99, value: "seaborn", label: "Seaborn" },
  { id: 74, value: "selenium", label: "Selenium" },
  { id: 132, value: "serverless", label: "Serverless" },
  { id: 66, value: "slack", label: "Slack" },
  { id: 130, value: "soap", label: "SOAP" },
  { id: 34, value: "spring", label: "Spring" },
  { id: 35, value: "springboot", label: "Spring Boot" },
  { id: 16, value: "sql", label: "SQL" },
  { id: 46, value: "sqlite", label: "SQLite" },
  { id: 48, value: "sqlserver", label: "SQL Server" },
  { id: 148, value: "ssl", label: "SSL/TLS" },
  { id: 136, value: "supabase", label: "Supabase" },
  { id: 24, value: "svelte", label: "Svelte" },
  { id: 127, value: "swagger", label: "Swagger" },
  { id: 11, value: "swift", label: "Swift" },
  { id: 37, value: "symfony", label: "Symfony" },
  { id: 109, value: "tableau", label: "Tableau" },
  { id: 86, value: "tailwindcss", label: "Tailwind CSS" },
  { id: 93, value: "tensorflow", label: "TensorFlow" },
  { id: 59, value: "terraform", label: "Terraform" },
  { id: 143, value: "tomcat", label: "Tomcat" },
  { id: 6, value: "typescript", label: "TypeScript" },
  { id: 112, value: "ubuntu", label: "Ubuntu" },
  { id: 138, value: "vercel", label: "Vercel" },
  { id: 119, value: "vim", label: "Vim" },
  { id: 68, value: "vite", label: "Vite" },
  { id: 120, value: "vscode", label: "VS Code" },
  { id: 23, value: "vue", label: "Vue.js" },
  { id: 67, value: "webpack", label: "Webpack" },
  { id: 115, value: "windows", label: "Windows" },
  { id: 81, value: "xamarin", label: "Xamarin" },
  { id: 123, value: "xcode", label: "Xcode" },
];

export const testSections = [
  { id: 1, value: "aptitude", label: "Aptitude" },
  { id: 2, value: "dsa", label: "Data Structures and Algorithms" },
  { id: 3, value: "computerscience", label: "Computer Science" },
  { id: 4, value: "databasequeries", label: "Database Queries" },
  { id: 5, value: "english", label: "English" },
  { id: 6, value: "generalknowledge", label: "General Knowledge" },
  { id: 7, value: "logicalreasoning", label: "Logical Reasoning" },
  { id: 8, value: "pseudocode", label: "Pseudocode" },
  { id: 9, value: "quantitative", label: "Quantitative" },
  { id: 10, value: "sqlqueries", label: "SQL Queries" },
  { id: 11, value: "technicalknowledge", label: "Technical Knowledge" },
  { id: 12, value: "verbal", label: "Verbal" },
];

export const inquiryTypes = [
  { id: 1, value: "accountissue", label: "Account Issue" },
  { id: 2, value: "billingpayment", label: "Billing & Payment" },
  { id: 3, value: "bugrepot", label: "Bug Report" },
  { id: 4, value: "cancelsubscription", label: "Cancel Subscription" },
  { id: 5, value: "customfeature", label: "Custom Feature Request" },
  { id: 6, value: "dataprivacy", label: "Data Privacy" },
  { id: 7, value: "feedback", label: "Feedback" },
  { id: 8, value: "general", label: "General Inquiry" },
  { id: 9, value: "interviewerissue", label: "Interviewer Issue" },
  { id: 10, value: "mockinterview", label: "Mock Interview" },
  { id: 11, value: "partnership", label: "Partnership" },
  { id: 12, value: "pricing", label: "Pricing" },
  { id: 13, value: "refund", label: "Refund Request" },
  { id: 14, value: "sales", label: "Sales" },
  { id: 15, value: "scheduling", label: "Scheduling" },
  { id: 16, value: "support", label: "Support" },
  { id: 17, value: "technical", label: "Technical Support" },
  { id: 18, value: "upgrade", label: "Upgrade Plan" },
];

export const genderOptions = [
  { id: 1, value: "male", label: "Male" },
  { id: 2, value: "female", label: "Female" },
  { id: 3, value: "prefer not to say", label: "Prefer not to say" },
];

export const JUDGE0_LANGUAGE_ID_TO_NAME_MAP = {
  javascript: 93,
  python: 71,
  java: 62,
  cpp: 54,
  csharp: 86,
  typescript: 74,
  go: 101,
  ruby: 72,
  php: 68,
  swift: 83,
  kotlin: 78,
  rust: 94,
  c: 50,
  r: 80,
};
